server:
  port: 8761
spring:
  application:
    name: Eureka-Server1
eureka:
  server:
    enable-self-preservation: false # ????
  instance:
    hostname: localhost:8761  # ??Eureka Server IP
  client:
    register-with-eureka: true # ???Eureka Server
    fetch-registry: true # ?Eureka????
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/ # Eureka server????
