server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${APPLICATION_NAME}
eureka:
  server:
    enable-self-preservation: false # 安全機制
  instance:
    hostname: ${EUREKA_HOSTNAME}  # 註冊Eureka Server IP
  client:
    register-with-eureka: true # 註冊至Eureka Server
    fetch-registry: true # 由Eureka取得資訊
    serviceUrl:
      defaultZone: http://${EUREKA_DEFAULT_ZONE}/eureka/ # Eureka server
