server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: openapi
          uri: http://localhost
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
#    use-root-path: true
    enabled: true # Disabling the swagger-ui
  api-docs:
    enabled: true # Disabling the /v3/api-docs endpoint