server:
  port: 8088
spring:
  profiles:
    active: native  # 讀取本地端
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/common
            - classpath:/config

sion:
  application:
    properties:
      env:
        enabled: true