spring:
  application:
    name: security-server
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  security:
    user:
      name: user
      password: 123
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  profiles:
    active: dev
server:
  port: 8787
#logging:
#  level:
#    root: DEBUG