spring:
  application:
    name: security-server
  security:
    user:
      name: user
      password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  profiles:
    active: dev
server:
  port: 8787
#logging:
#  level:
#    root: DEBUG