server:
  port: 81

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/mysqldb?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: password

#springfox:
#  documentation:
#    auto-startup: false

logging:
  level:
    org:
      springframework: ERROR
