eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: 8080
