spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gateway
    username: sa
    password: sa
  h2:
    console:
      enabled: true
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: 8888
