spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST_ONE}/eureka/,http://${EUREKA_SERVER_HOST_TWO}/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}
server:
  port: ${SERVER_PORT}
