spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gateway
    username: sa
    password: sa
  h2:
    console:
      enabled: true
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER1}/eureka/,http://${EUREKA_SERVER2}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${HOST_IP}:${SERVER_PORT}
logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: ${SERVER_PORT}
