server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: Server-Provider
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
