server:
  port: 8081
spring:
  application:
    name: todo-service

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    enabled: true # Disabling the swagger-ui
  api-docs:
    enabled: true # Disabling the /v3/api-docs endpoint