server:
  port: 1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: Server-Admin
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka